services:
  - type: web
    name: cdi-edi-design-platform-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5007
      - key: CLIENT_ORIGIN
        value: https://effulgent-twilight-1ce68d.netlify.app
      - key: SESSION_SECRET
        generateValue: true
